/**
 * @license
 * Copyright 2025 AionUi (aionui.com)
 * SPDX-License-Identifier: Apache-2.0
 */

export type IntegrationDefinition = {
  envKey: string;
  label: string;
  link: string;
  docsLabel: string;
  helperLink?: string;
  helperLabel?: string;
  group: 'core' | 'cloud' | 'media' | 'ops' | 'developer';
  authMode?: 'auth0' | 'oauth' | 'api-key' | 'local';
  priority?: 'must' | 'recommended' | 'optional';
  setupHint?: string;
};

export const INTEGRATION_KEYS: IntegrationDefinition[] = [
  {
    envKey: 'AUTH0_DOMAIN',
    label: 'Auth0 Domain',
    link: 'https://manage.auth0.com/dashboard/',
    docsLabel: 'Auth0 Dashboard',
    helperLink: 'https://auth0.com/docs/get-started/applications/application-settings',
    helperLabel: 'Application settings',
    group: 'ops',
    authMode: 'auth0',
    priority: 'must',
    setupHint: 'Use one Auth0 tenant as central login for dashboards and client portals.',
  },
  {
    envKey: 'AUTH0_CLIENT_ID',
    label: 'Auth0 Client ID',
    link: 'https://manage.auth0.com/dashboard/',
    docsLabel: 'Auth0 Dashboard',
    helperLink: 'https://auth0.com/docs/get-started/applications/application-settings',
    helperLabel: 'Application settings',
    group: 'ops',
    authMode: 'auth0',
    priority: 'must',
    setupHint: 'Public application identifier for Auth0 login.',
  },
  {
    envKey: 'AUTH0_CLIENT_SECRET',
    label: 'Auth0 Client Secret',
    link: 'https://manage.auth0.com/dashboard/',
    docsLabel: 'Auth0 Dashboard',
    helperLink: 'https://auth0.com/docs/get-started/applications/application-settings',
    helperLabel: 'Application settings',
    group: 'ops',
    authMode: 'auth0',
    priority: 'must',
    setupHint: 'Secret for server-side Auth0 token exchange. Keep it private.',
  },
  {
    envKey: 'AUTH0_AUDIENCE',
    label: 'Auth0 API Audience',
    link: 'https://manage.auth0.com/dashboard/',
    docsLabel: 'Auth0 APIs',
    helperLink: 'https://auth0.com/docs/get-started/apis',
    helperLabel: 'Create API',
    group: 'ops',
    authMode: 'auth0',
    priority: 'recommended',
    setupHint: 'Use when dashboards call a protected backend/API.',
  },
  {
    envKey: 'OPENAI_API_BASE',
    label: 'OpenAI API Base',
    link: 'https://platform.openai.com/docs/api-reference',
    docsLabel: 'OpenAI API Reference',
    group: 'core',
  },
  {
    envKey: 'OPENAI_API_KEY',
    label: 'OpenAI API Key',
    link: 'https://platform.openai.com/api-keys',
    docsLabel: 'OpenAI API Keys',
    group: 'core',
    authMode: 'api-key',
    priority: 'recommended',
  },
  {
    envKey: 'ANTHROPIC_API_BASE',
    label: 'Anthropic API Base',
    link: 'https://docs.anthropic.com/',
    docsLabel: 'Anthropic Docs',
    group: 'core',
  },
  {
    envKey: 'ANTHROPIC_API_KEY',
    label: 'Anthropic API Key',
    link: 'https://docs.anthropic.com/en/api/api-keys',
    docsLabel: 'Anthropic API keys',
    group: 'core',
    authMode: 'api-key',
    priority: 'recommended',
  },
  {
    envKey: 'CLAUDE_API_KEY',
    label: 'Claude API Key',
    link: 'https://docs.anthropic.com/en/docs/quickstart',
    docsLabel: 'Claude docs',
    group: 'core',
    authMode: 'api-key',
    priority: 'optional',
  },
  {
    envKey: 'CLAUDE_ACCESS_TOKEN',
    label: 'Claude Access Token',
    link: 'https://claude.ai/settings/tokens',
    docsLabel: 'Claude token settings',
    group: 'core',
    authMode: 'oauth',
    priority: 'recommended',
  },
  {
    envKey: 'GOOGLE_APPLICATION_CREDENTIALS_JSON',
    label: 'Google Credentials JSON',
    link: 'https://cloud.google.com/docs/authentication/provide-credentials-adc',
    docsLabel: 'Google auth docs',
    group: 'cloud',
    authMode: 'api-key',
    priority: 'optional',
  },
  {
    envKey: 'GOOGLE_API_KEY',
    label: 'Google API Key',
    link: 'https://aistudio.google.com/app/apikey',
    docsLabel: 'Google AI Studio',
    group: 'cloud',
    authMode: 'api-key',
    priority: 'recommended',
  },
  {
    envKey: 'GEMINI_API_KEY',
    label: 'Gemini API Key',
    link: 'https://aistudio.google.com/app/apikey',
    docsLabel: 'Gemini API key',
    group: 'cloud',
    authMode: 'api-key',
    priority: 'recommended',
  },
  {
    envKey: 'STITCH_API_KEY',
    label: 'Google Stitch API Key',
    link: 'https://stitch.withgoogle.com/',
    docsLabel: 'Google Stitch',
    helperLink: 'https://stitch.withgoogle.com/docs/mcp/setup/',
    helperLabel: 'Stitch MCP setup',
    group: 'developer',
    authMode: 'api-key',
    priority: 'recommended',
    setupHint: 'Use this for Google Stitch remote MCP design-to-code workflows.',
  },
  {
    envKey: 'OPENROUTER_API_KEY',
    label: 'OpenRouter API Key',
    link: 'https://openrouter.ai/settings/keys',
    docsLabel: 'OpenRouter keys',
    group: 'cloud',
    authMode: 'api-key',
    priority: 'recommended',
  },
  {
    envKey: 'GROQ_API_KEY',
    label: 'Groq API Key',
    link: 'https://console.groq.com/keys',
    docsLabel: 'Groq keys',
    group: 'cloud',
    authMode: 'api-key',
    priority: 'optional',
  },
  {
    envKey: 'PERPLEXITY_API_KEY',
    label: 'Perplexity API Key',
    link: 'https://www.perplexity.ai/settings/api',
    docsLabel: 'Perplexity API',
    group: 'cloud',
    authMode: 'api-key',
    priority: 'recommended',
  },
  {
    envKey: 'XAI_API_KEY',
    label: 'xAI / Grok API Key',
    link: 'https://console.x.ai/',
    docsLabel: 'xAI Console',
    group: 'cloud',
    authMode: 'api-key',
    priority: 'optional',
  },
  {
    envKey: 'DEEPSEEK_API_KEY',
    label: 'DeepSeek API Key',
    link: 'https://platform.deepseek.com/api_keys',
    docsLabel: 'DeepSeek keys',
    group: 'cloud',
    authMode: 'api-key',
    priority: 'recommended',
  },
  {
    envKey: 'HUGGINGFACE_API_KEY',
    label: 'Hugging Face API Key',
    link: 'https://huggingface.co/settings/tokens',
    docsLabel: 'HF token settings',
    group: 'developer',
    authMode: 'api-key',
    priority: 'recommended',
  },
  {
    envKey: 'HF_TOKEN',
    label: 'HF Token',
    link: 'https://huggingface.co/settings/tokens',
    docsLabel: 'HF token settings',
    group: 'developer',
    authMode: 'api-key',
    priority: 'recommended',
  },
  {
    envKey: 'OLLAMA_API_KEY',
    label: 'Ollama API Key',
    link: 'https://ollama.com/',
    docsLabel: 'Ollama',
    group: 'developer',
    authMode: 'oauth',
    priority: 'recommended',
  },
  {
    envKey: 'KRYVAI_API_KEY',
    label: 'Kryven API Key (legacy)',
    link: 'https://kryven.cc/docs/',
    docsLabel: 'Kryven docs',
    helperLink: 'https://kryven.cc/docs/',
    helperLabel: 'Get Kryven key',
    group: 'developer',
    authMode: 'api-key',
    priority: 'optional',
  },
  {
    envKey: 'KRYVEN_API_KEY',
    label: 'Kryven API Key',
    link: 'https://kryven.cc/docs/',
    docsLabel: 'Kryven docs',
    helperLink: 'https://kryven.cc/docs/',
    helperLabel: 'Get Kryven key',
    group: 'developer',
    authMode: 'api-key',
    priority: 'optional',
  },
  {
    envKey: 'SUNO_COOKIE',
    label: 'Suno Cookie',
    link: 'https://suno.com/',
    docsLabel: 'Suno',
    group: 'media',
    authMode: 'oauth',
    priority: 'optional',
  },
  {
    envKey: 'DISCORD_BOT_TOKEN',
    label: 'Discord Bot Token',
    link: 'https://discord.com/developers/applications',
    docsLabel: 'Discord Developer Portal',
    group: 'ops',
    authMode: 'api-key',
    priority: 'optional',
  },
  {
    envKey: 'TELEGRAM_BOT_TOKEN',
    label: 'Telegram Bot Token',
    link: 'https://core.telegram.org/bots/tutorial',
    docsLabel: 'Telegram bot docs',
    group: 'ops',
    authMode: 'api-key',
    priority: 'recommended',
  },
  {
    envKey: 'LIVEKIT_API_KEY',
    label: 'LiveKit API Key',
    link: 'https://docs.livekit.io/realtime/security/api-keys/',
    docsLabel: 'LiveKit API keys',
    group: 'media',
    authMode: 'api-key',
    priority: 'recommended',
  },
  {
    envKey: 'LIVEKIT_API_SECRET',
    label: 'LiveKit API Secret',
    link: 'https://docs.livekit.io/realtime/security/api-keys/',
    docsLabel: 'LiveKit API keys',
    group: 'media',
    authMode: 'api-key',
    priority: 'recommended',
  },
  {
    envKey: 'LIVEKIT_URL',
    label: 'LiveKit URL',
    link: 'https://docs.livekit.io/home/self-hosting/docker/',
    docsLabel: 'LiveKit host setup',
    group: 'media',
    authMode: 'local',
    priority: 'recommended',
  },
  {
    envKey: 'CLICKUP_API_TOKEN',
    label: 'ClickUp API Token',
    link: 'https://help.clickup.com/hc/en-us/articles/6303420891089-API-Token',
    docsLabel: 'ClickUp API token',
    group: 'ops',
    authMode: 'api-key',
    priority: 'optional',
  },
  {
    envKey: 'KAGGLE_USERNAME',
    label: 'Kaggle Username',
    link: 'https://www.kaggle.com/settings',
    docsLabel: 'Kaggle settings',
    group: 'developer',
    authMode: 'api-key',
    priority: 'optional',
  },
  {
    envKey: 'KAGGLE_KEY',
    label: 'Kaggle API Key',
    link: 'https://www.kaggle.com/settings',
    docsLabel: 'Kaggle settings',
    group: 'developer',
    authMode: 'api-key',
    priority: 'optional',
  },
  {
    envKey: 'WOLFRAM_ALPHA_API_KEY',
    label: 'Wolfram Alpha API Key',
    link: 'https://products.wolframalpha.com/api/',
    docsLabel: 'Wolfram Alpha API',
    group: 'developer',
    authMode: 'api-key',
    priority: 'optional',
  },
  {
    envKey: 'CLAW3D_API_KEY',
    label: 'Claw3D API Key',
    link: 'https://app.claw3d.ai/',
    docsLabel: 'Claw3D',
    group: 'media',
    authMode: 'api-key',
    priority: 'optional',
  },
  {
    envKey: 'GITLAB_TOKEN',
    label: 'GitLab Token',
    link: 'https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html',
    docsLabel: 'GitLab PAT guide',
    group: 'developer',
    authMode: 'api-key',
    priority: 'optional',
  },
  {
    envKey: 'GITHUB_TOKEN',
    label: 'GitHub Token',
    link: 'https://github.com/settings/tokens',
    docsLabel: 'GitHub tokens',
    group: 'developer',
    authMode: 'api-key',
    priority: 'recommended',
  },
  {
    envKey: 'DEVIN_API_KEY',
    label: 'Devin API Key',
    link: 'https://app.devin.ai/settings',
    docsLabel: 'Devin settings',
    group: 'developer',
    authMode: 'api-key',
    priority: 'optional',
  },
  {
    envKey: 'RESEND_API_KEY',
    label: 'Resend API Key',
    link: 'https://resend.com/api-keys',
    docsLabel: 'Resend keys',
    group: 'ops',
    authMode: 'api-key',
    priority: 'recommended',
  },
  {
    envKey: 'NOIZ_API_KEY',
    label: 'Noiz.ai API Key',
    link: 'https://noiz.ai/',
    docsLabel: 'Noiz.ai',
    helperLink: 'https://noiz.ai/',
    helperLabel: 'Open Noiz.ai',
    group: 'media',
    authMode: 'api-key',
    priority: 'recommended',
    setupHint: 'Use this for Noiz.ai audio/media generation routes when they are enabled.',
  },
  {
    envKey: 'HOSTINGER_API_TOKEN',
    label: 'Hostinger API Token',
    link: 'https://developers.hostinger.com/',
    docsLabel: 'Hostinger API',
    group: 'ops',
    authMode: 'api-key',
    priority: 'recommended',
  },
];

export const INTEGRATION_KEY_ALLOWLIST = INTEGRATION_KEYS.map((item) => item.envKey);
